/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { AbujaEvent, TicketPlan, User, EventStatus, Booking, Notification } from './types';

// Let's seed users
export const INITIAL_USERS: User[] = [
  {
    id: 'admin',
    role: 'Admin',
    email: 'admin@abujaevents.com',
    fullName: 'Abuja Events Admin',
    phone: '+234 801 234 5678',
  },
  {
    id: 'org1',
    role: 'Organizer',
    email: 'events@capitalcreatives.com',
    fullName: 'Chidi Okafor',
    phone: '+234 809 111 2222',
    businessName: 'Capital Creatives Agency',
    brandLogo: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=200',
    businessAddress: '12 Aminu Kano Crescent, Wuse II, Abuja',
    instagram: '@capitalcreatives',
    facebook: 'facebook.com/capitalcreatives',
    website: 'capitalcreatives.com',
  },
  {
    id: 'org2',
    role: 'Organizer',
    email: 'hello@abujatechhub.ng',
    fullName: 'Fatima Bello',
    phone: '+234 803 333 4444',
    businessName: 'Abuja Tech Hub',
    brandLogo: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?auto=format&fit=crop&q=80&w=200',
    businessAddress: '45 Constitution Ave, Central Business District, Abuja',
    instagram: '@abujatechhub',
    facebook: 'facebook.com/abujatechhub',
    website: 'abujatechhub.ng',
  },
  {
    id: 'buyer1',
    role: 'Buyer',
    email: 'buyer@gmail.com',
    fullName: 'Tunde Johnson',
    phone: '+234 812 345 6789',
    instagram: '@tunde_j',
    facebook: 'facebook.com/tundej',
  },
];

// Areas of Abuja
export const ABUJA_AREAS = [
  'Wuse II',
  'Maitama',
  'Garki',
  'Asokoro',
  'Gwarinpa',
  'Jabi',
  'Central Business District',
  'Utako',
  'Apo',
  'Lokogoma',
];

// Categories
export const EVENT_CATEGORIES = [
  'Music & Concerts',
  'Food & Drink',
  'Arts & Culture',
  'Tech & Business',
  'Sports & Fitness',
  'Nightlife & Parties',
  'Comedy & Theatre',
];

// Let's seed events.
// The current local date is 2026-07-08 (Wednesday).
// Today's events: 2026-07-08
// Tomorrow's events: 2026-07-09
// Weekend events: 2026-07-10 (Fri), 2026-07-11 (Sat), 2026-07-12 (Sun)
// Upcoming events: 2026-07-15 etc.
// Past event to test archive: 2026-07-06
export const INITIAL_EVENTS: AbujaEvent[] = [
  {
    id: 'event-1',
    organizerId: 'org1',
    title: 'Capital Food & Wine Festival',
    subtitle: 'The Ultimate Culinary Experience in the Heart of Abuja',
    description: 'Join us for a spectacular day of gourmet food tasting, premium wine pairings, and live music from Abuja’s top bands. Featuring over 30 local food vendors, chef masterclasses, and an exclusive wine garden. Perfect for families and friends looking to explore Abuja’s vibrant culinary scene.',
    category: 'Food & Drink',
    tags: ['Food', 'Wine', 'Festival', 'Live Music', 'Maitama'],
    flyerUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&q=80&w=800',
    organizerLogo: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=200',
    backgroundBanner: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&q=80&w=1200',
    date: '2026-07-08', // Today
    openingTime: '12:00',
    closingTime: '22:00',
    timezone: 'WAT (UTC+1)',
    venueName: 'Millennium Park',
    streetAddress: 'Three Arms Zone, Maitama',
    area: 'Maitama',
    landmark: 'Opposite Transcorp Hilton',
    googleMapLink: 'https://maps.google.com/?q=Millennium+Park+Abuja',
    organizerName: 'Capital Creatives Agency',
    phone: '+234 809 111 2222',
    email: 'events@capitalcreatives.com',
    website: 'capitalcreatives.com',
    instagram: '@capitalcreatives',
    facebook: 'facebook.com/capitalcreatives',
    whatsapp: 'https://wa.me/2348091112222',
    gallery: [
      'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&q=80&w=500',
      'https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&q=80&w=500',
      'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&q=80&w=500'
    ],
    faqs: [
      { question: 'Is parking available?', answer: 'Yes, secure parking is available at the venue gates with security guards present.' },
      { question: 'Can I bring children?', answer: 'Absolutely! There is a kids zone with bouncy castles and face painting.' },
      { question: 'Are outside drinks allowed?', answer: 'No, outside food and drinks are strictly prohibited.' }
    ],
    ageRestriction: 'All Ages',
    dressCode: 'Casual / Picnic Chic',
    parking: 'Available & Secured',
    refundPolicy: 'No refunds, tickets are transferable.',
    status: EventStatus.TicketingActive,
    isFeatured: true,
    interestedCount: 245,
    createdAt: '2026-07-01T10:00:00Z',
  },
  {
    id: 'event-2',
    organizerId: 'org2',
    title: 'Abuja Tech Summit 2026',
    subtitle: 'Connecting Innovators, Founders, and Investors in West Africa',
    description: 'The premier technology conference in Abuja, gathering over 1,000 tech professionals, founders, and venture capitalists. Explore tracks on AI, Fintech, Web3, and Tech Talent in Nigeria. Gain insights from seasoned founders and meet your next partner or investor.',
    category: 'Tech & Business',
    tags: ['Tech', 'Conference', 'Startup', 'Networking', 'AI'],
    flyerUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&q=80&w=800',
    organizerLogo: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?auto=format&fit=crop&q=80&w=200',
    backgroundBanner: 'https://images.unsplash.com/photo-1515187029135-18ee286d815b?auto=format&fit=crop&q=80&w=1200',
    date: '2026-07-09', // Tomorrow
    openingTime: '09:00',
    closingTime: '17:00',
    timezone: 'WAT (UTC+1)',
    venueName: 'International Conference Centre (ICC)',
    streetAddress: '900 Herbert Macaulay Way, Central Business District',
    area: 'Central Business District',
    landmark: 'Near Radio House',
    googleMapLink: 'https://maps.google.com/?q=International+Conference+Centre+Abuja',
    organizerName: 'Abuja Tech Hub',
    phone: '+234 803 333 4444',
    email: 'hello@abujatechhub.ng',
    website: 'abujatechhub.ng',
    instagram: '@abujatechhub',
    facebook: 'facebook.com/abujatechhub',
    whatsapp: 'https://wa.me/2348033334444',
    gallery: [
      'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=500',
      'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&q=80&w=500',
      'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&q=80&w=500'
    ],
    faqs: [
      { question: 'Will there be lunch?', answer: 'Yes, lunch and coffee breaks are included in VIP and Executive ticket classes.' },
      { question: 'Are there student discounts?', answer: 'Yes, a limited number of student tickets are available upon presenting valid ID.' }
    ],
    ageRestriction: '18+',
    dressCode: 'Business Casual',
    parking: 'Ample parking available inside the ICC premises.',
    refundPolicy: 'Refunds up to 7 days before event.',
    status: EventStatus.TicketingActive,
    isFeatured: true,
    interestedCount: 512,
    createdAt: '2026-07-02T11:30:00Z',
  },
  {
    id: 'event-3',
    organizerId: 'org1',
    title: 'Acoustic & Poetry Night Abuja',
    subtitle: 'An intimate evening of beautiful melodies and spoken word art',
    description: 'Escape the Abuja noise and enjoy a beautiful evening of candlelight poetry and acoustic soul music. Featuring incredible Abuja indie artists, poetry slams, and open mic segments. A perfect intimate date night or relaxing social evening.',
    category: 'Arts & Culture',
    tags: ['Poetry', 'Acoustic', 'Music', 'Spoken Word', 'Wuse II'],
    flyerUrl: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&q=80&w=800',
    organizerLogo: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=200',
    backgroundBanner: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&q=80&w=1200',
    date: '2026-07-11', // Saturday (Weekend)
    openingTime: '18:00',
    closingTime: '22:00',
    timezone: 'WAT (UTC+1)',
    venueName: 'Thought Pyramid Art Centre',
    streetAddress: '18 Libreville St, Wuse II',
    area: 'Wuse II',
    landmark: 'Near Shiroro Hotel',
    googleMapLink: 'https://maps.google.com/?q=Thought+Pyramid+Art+Centre+Abuja',
    organizerName: 'Capital Creatives Agency',
    phone: '+234 809 111 2222',
    email: 'events@capitalcreatives.com',
    website: 'capitalcreatives.com',
    instagram: '@capitalcreatives',
    facebook: 'facebook.com/capitalcreatives',
    whatsapp: 'https://wa.me/2348091112222',
    gallery: [
      'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?auto=format&fit=crop&q=80&w=500',
      'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?auto=format&fit=crop&q=80&w=500'
    ],
    faqs: [
      { question: 'Is seating guaranteed?', answer: 'Seating is first-come, first-served. Early arrival is highly recommended!' },
      { question: 'Is there an open mic segment?', answer: 'Yes, registration for open mic begins exactly at 17:30 at the entrance.' }
    ],
    ageRestriction: '16+',
    dressCode: 'Smart Casual / Artsy',
    parking: 'Limited street parking with active vigilante security.',
    refundPolicy: 'No refunds.',
    status: EventStatus.TicketingActive,
    isFeatured: false,
    interestedCount: 189,
    createdAt: '2026-07-03T15:00:00Z',
  },
  {
    id: 'event-4',
    organizerId: 'org1',
    title: 'Abuja Polo Club Charity Cup',
    subtitle: 'High stakes polo for a wonderful cause',
    description: 'Experience the sport of kings in Maitama, Abuja. A prestigious charity tournament supporting educational facilities for underprivileged children. Watch competitive matches, enjoy equestrian showcases, and network with elites at the VIP lounge.',
    category: 'Sports & Fitness',
    tags: ['Polo', 'Sports', 'Equestrian', 'Charity', 'Maitama'],
    flyerUrl: 'https://images.unsplash.com/photo-1551834900-a1975e54d588?auto=format&fit=crop&q=80&w=800',
    organizerLogo: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=200',
    backgroundBanner: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=1200',
    date: '2026-07-12', // Sunday (Weekend)
    openingTime: '14:00',
    closingTime: '19:00',
    timezone: 'WAT (UTC+1)',
    venueName: 'Abuja Polo Club',
    streetAddress: '1 Muritala Mohammed Way, Maitama',
    area: 'Maitama',
    landmark: 'Polo Club Gate',
    googleMapLink: 'https://maps.google.com/?q=Abuja+Polo+Club',
    organizerName: 'Capital Creatives Agency',
    phone: '+234 809 111 2222',
    email: 'events@capitalcreatives.com',
    website: 'capitalcreatives.com',
    instagram: '@capitalcreatives',
    facebook: 'facebook.com/capitalcreatives',
    whatsapp: 'https://wa.me/2348091112222',
    gallery: [
      'https://images.unsplash.com/photo-1551834900-a1975e54d588?auto=format&fit=crop&q=80&w=500'
    ],
    faqs: [
      { question: 'What is the dress code?', answer: 'Polo elegant. Hats and dresses for ladies, smart shirts/blazers for gents.' }
    ],
    ageRestriction: 'All Ages',
    dressCode: 'Polo Elegant',
    parking: 'Secure parking inside the club grounds.',
    refundPolicy: 'Non-refundable.',
    status: EventStatus.Approved, // Only Approved, so tickets are 'Coming Soon' (Buy Ticket disabled)
    isFeatured: false,
    interestedCount: 320,
    createdAt: '2026-07-04T09:00:00Z',
  },
  {
    id: 'event-5',
    organizerId: 'org2',
    title: 'Gwarinpa Tech Founder Meetup',
    subtitle: 'Unwinding with fellow builders and founders over drinks',
    description: 'An informal networking event for technology founders, engineers, and product builders based in the Gwarinpa and Jabi axis. Let’s talk about product launches, scaling in Nigeria, and fund-raising, in a completely relaxed environment.',
    category: 'Tech & Business',
    tags: ['Tech', 'Meetup', 'Founders', 'Networking', 'Gwarinpa'],
    flyerUrl: 'https://images.unsplash.com/photo-1556761175-4b46a572b786?auto=format&fit=crop&q=80&w=800',
    organizerLogo: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?auto=format&fit=crop&q=80&w=200',
    backgroundBanner: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&q=80&w=1200',
    date: '2026-07-15', // Upcoming
    openingTime: '17:00',
    closingTime: '20:00',
    timezone: 'WAT (UTC+1)',
    venueName: 'The Cube Workspace',
    streetAddress: '4th Avenue, Gwarinpa',
    area: 'Gwarinpa',
    landmark: 'Beside Zenith Bank',
    googleMapLink: 'https://maps.google.com/?q=Zenith+Bank+Gwarinpa',
    organizerName: 'Abuja Tech Hub',
    phone: '+234 803 333 4444',
    email: 'hello@abujatechhub.ng',
    website: 'abujatechhub.ng',
    instagram: '@abujatechhub',
    facebook: 'facebook.com/abujatechhub',
    whatsapp: 'https://wa.me/2348033334444',
    gallery: [],
    faqs: [],
    ageRestriction: '18+',
    dressCode: 'Casual',
    parking: 'Street parking.',
    refundPolicy: 'Free event.',
    status: EventStatus.PendingReview, // Pending review, not yet approved! Shows in Admin Dashboard notifications.
    isFeatured: false,
    interestedCount: 42,
    createdAt: '2026-07-06T14:20:00Z',
  },
  {
    id: 'event-6',
    organizerId: 'org1',
    title: 'Wuse Epic Saturday Night Rave',
    subtitle: 'The grandest nightlife experience in the capital city',
    description: 'Get ready for Abuja’s premier clubbing experience at Garki. Incredible high-definition sound and light show, featuring three of the hottest DJs in Nigeria. Dance until sunrise with custom cocktails, laser setups, and unmatched high-octane energy.',
    category: 'Nightlife & Parties',
    tags: ['Nightlife', 'Party', 'DJ', 'Clubbing', 'Garki'],
    flyerUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&q=80&w=800',
    organizerLogo: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=200',
    backgroundBanner: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80&w=1200',
    date: '2026-07-11', // Saturday (Weekend)
    openingTime: '22:00',
    closingTime: '05:00',
    timezone: 'WAT (UTC+1)',
    venueName: 'The Vault Lounge',
    streetAddress: 'Plot 312 Garki Area 11',
    area: 'Garki',
    landmark: 'Behind Dunamis Church',
    googleMapLink: 'https://maps.google.com/?q=The+Vault+Lounge+Abuja',
    organizerName: 'Capital Creatives Agency',
    phone: '+234 809 111 2222',
    email: 'events@capitalcreatives.com',
    website: 'capitalcreatives.com',
    instagram: '@capitalcreatives',
    facebook: 'facebook.com/capitalcreatives',
    whatsapp: 'https://wa.me/2348091112222',
    gallery: [],
    faqs: [],
    ageRestriction: '21+',
    dressCode: 'Glamorous & Sleek',
    parking: 'Valet parking available.',
    refundPolicy: 'No refunds.',
    status: EventStatus.Approved, // Tickets not enabled yet
    isFeatured: false,
    interestedCount: 154,
    createdAt: '2026-07-07T16:00:00Z',
  },
  {
    id: 'event-7',
    organizerId: 'org1',
    title: 'Past Concert: Abuja Live In Colour',
    subtitle: 'The Colourful Music Experience of the Year',
    description: 'A beautiful paint and music party that happened last week in Wuse II.',
    category: 'Music & Concerts',
    tags: ['Music', 'Party', 'Past'],
    flyerUrl: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&q=80&w=800',
    organizerLogo: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=200',
    backgroundBanner: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&q=80&w=1200',
    date: '2026-07-05', // Ended & archived (Ended since date < today)
    openingTime: '15:00',
    closingTime: '23:00',
    timezone: 'WAT (UTC+1)',
    venueName: 'Millennium Park',
    streetAddress: 'Maitama',
    area: 'Maitama',
    landmark: 'Maitama Gate',
    googleMapLink: '',
    organizerName: 'Capital Creatives Agency',
    phone: '+234 809 111 2222',
    email: 'events@capitalcreatives.com',
    website: 'capitalcreatives.com',
    instagram: '@capitalcreatives',
    facebook: '',
    whatsapp: '',
    gallery: [],
    faqs: [],
    ageRestriction: 'All Ages',
    dressCode: 'White Clothes',
    parking: 'Available',
    refundPolicy: 'None',
    status: EventStatus.Archived, // Automatically archived (ended 24h later)
    isFeatured: false,
    interestedCount: 380,
    createdAt: '2026-06-20T10:00:00Z',
  },
];

export const INITIAL_TICKET_PLANS: TicketPlan[] = [
  // For Event 1 (Food & Wine)
  {
    id: 'tp-1-1',
    eventId: 'event-1',
    name: 'Regular Entrance',
    price: 5000,
    availableQuantity: 300,
    maxPurchaseLimit: 5,
    description: 'Includes gate entrance and access to all food stalls and the concert stage.',
    color: '#3B82F6', // Blue
    displayOrder: 1,
  },
  {
    id: 'tp-1-2',
    eventId: 'event-1',
    name: 'VIP Tasting Experience',
    price: 15000,
    availableQuantity: 100,
    maxPurchaseLimit: 3,
    description: 'Includes premium wine glass, 3 complimentary wine tasting vouchers, and VIP lounge access.',
    color: '#8B5CF6', // Purple
    displayOrder: 2,
  },
  {
    id: 'tp-1-3',
    eventId: 'event-1',
    name: 'VVIP Cabana Table',
    price: 150000,
    availableQuantity: 10,
    maxPurchaseLimit: 1,
    description: 'Private cabana for 6 people. Includes 3 premium champagne bottles, gourmet platter, and dedicated waiter service.',
    color: '#D97706', // Amber/Gold
    displayOrder: 3,
  },

  // For Event 2 (Tech Summit)
  {
    id: 'tp-2-1',
    eventId: 'event-2',
    name: 'General Attendee',
    price: 10000,
    availableQuantity: 500,
    maxPurchaseLimit: 4,
    description: 'Access to keynote sessions, main panels, and exhibition hall.',
    color: '#10B981', // Green
    displayOrder: 1,
  },
  {
    id: 'tp-2-2',
    eventId: 'event-2',
    name: 'VIP Delegate Pass',
    price: 40000,
    availableQuantity: 150,
    maxPurchaseLimit: 2,
    description: 'Access to premium networking lunch, private lounge, VIP seating area, and presentation slides bundle.',
    color: '#F59E0B', // Amber
    displayOrder: 2,
  },

  // For Event 3 (Acoustic Night)
  {
    id: 'tp-3-1',
    eventId: 'event-3',
    name: 'Single Entry',
    price: 7500,
    availableQuantity: 80,
    maxPurchaseLimit: 4,
    description: 'Includes 1 complimentary cocktail or mocktail.',
    color: '#EF4444', // Red
    displayOrder: 1,
  },
  {
    id: 'tp-3-2',
    eventId: 'event-3',
    name: 'Couples Cozy Pass',
    price: 13000,
    availableQuantity: 30,
    maxPurchaseLimit: 2,
    description: 'Entrance for two with candlelit desk seating and a shared complimentary pizza + 2 drinks.',
    color: '#EC4899', // Pink
    displayOrder: 2,
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'bk-1',
    eventId: 'event-1',
    buyerId: 'buyer1',
    ticketPlanId: 'tp-1-1',
    quantity: 2,
    totalAmount: 10000,
    status: 'Confirmed',
    bookingReference: 'AE-FW-73921',
    createdAt: '2026-07-05T12:00:00Z',
    customerDetails: {
      fullName: 'Tunde Johnson',
      email: 'buyer@gmail.com',
      phone: '+234 812 345 6789',
    },
  },
  {
    id: 'bk-2',
    eventId: 'event-1',
    buyerId: 'buyer1',
    ticketPlanId: 'tp-1-2',
    quantity: 1,
    totalAmount: 15000,
    status: 'Pending', // Pending admin confirmation
    bookingReference: 'AE-FW-89311',
    createdAt: '2026-07-08T10:30:00Z',
    customerDetails: {
      fullName: 'Tunde Johnson',
      email: 'buyer@gmail.com',
      phone: '+234 812 345 6789',
    },
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    userId: 'org1',
    title: 'Event Published Successfully',
    message: 'Your event "Capital Food & Wine Festival" is published and pending review by the administrator.',
    type: 'success',
    createdAt: '2026-07-01T10:00:00Z',
    isRead: false,
  },
  {
    id: 'notif-2',
    userId: 'admin',
    title: 'New Event Pending Review',
    message: 'Organizer "Abuja Tech Hub" created a new event "Gwarinpa Tech Founder Meetup" that requires approval.',
    type: 'warning',
    createdAt: '2026-07-06T14:20:00Z',
    isRead: false,
  },
  {
    id: 'notif-3',
    userId: 'buyer1',
    title: 'Booking Created',
    message: 'Your order for VIP Tasting Experience is submitted. Please make the bank transfer to complete your booking.',
    type: 'info',
    createdAt: '2026-07-08T10:30:00Z',
    isRead: false,
  },
];
